version: 2.1

jobs:
  install:
    docker:
      - image: circleci/node:14-buster
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
            keys:
              - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
              - dependencies-
      - run:
          name : Intsall deps
          command: |
            yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}

  test_build:
    docker:
      - image: circleci/node:14-buster
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            - dependencies-
      - run:
          name: Test and build
          command: |
              yarn test && yarn build
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - public
  deploy:
    docker:
      - image: circleci/node:14-buster
    working_directory: ~/project
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            - dependencies-
      - run:
          name: install netlify cli
          command: yarn add netlify-cli -g
      - run:
          name: Deploy react app
          command: yarn netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir /home/circleci/project/public --prod
workflows:
  build_test_deploy:
    jobs:
      - install
      - test_build:
          requires:
            - install
      - deploy:
          requires:
            - test_build